name: Trigger Skypoint Social Posts

on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Call the API endpoint to trigger posts
        run: curl --fail 'https://skypoint-social.vercel.app/api/trigger-posts'