name: Trigger Skypoint Social Posts

on:
  schedule:
    # Runs every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Call the API endpoint to trigger posts
        run: curl --fail 'https://socia.skypoint.dev/api/trigger-posts'